[servers]

[servers.go-sbot]
label = "go-sbot"
command = "/Users/agarzia/ssbc/go-ssb/go-sbot"
start = ["-localdiscov", "-localadv", "-wslis \":8990\"", "-l \":8009\""]
check = "-version"
auto_start = false


[servers.patchwork]
label = "Patchwork"
command = "/Applications/Patchwork.app/Contents/MacOS/Patchwork"
start = []
check = ""
auto_start = false
