# https://www.appveyor.com/docs/lang/nodejs-iojs/

cache:
  - node_modules

init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version

build: off
