# This file has been generated by node2nix 1.6.0
# but has been edited to include the systrayhelper

{ pkgs ? import ~/nixpkgs { inherit system; }
, system ? builtins.currentSystem
, nodejs ? pkgs."nodejs-8_x"
, systrayhelper ? pkgs.systrayhelper
}:

let
  globalBuildInputs = pkgs.lib.attrValues (import ./supplement.nix {
    inherit nodeEnv;
    inherit (pkgs) fetchurl fetchgit;
  }) ++ [ systrayhelper ];
  nodeEnv = import ./node-env.nix {
    inherit (pkgs) stdenv python2 utillinux runCommand writeTextFile;
    inherit nodejs;
    libtool = if pkgs.stdenv.isDarwin then pkgs.darwin.cctools else null;
  };
in
import ./node-packages.nix {
  inherit (pkgs) fetchurl fetchgit;
  inherit nodeEnv globalBuildInputs;
}